package controller;

import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.util.Duration;
import model.User;
import util.Sesi;
import util.ViewFactory;
import java.time.LocalDate;
import java.time.LocalTime;
import javafx.animation.Animation;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextArea;
import javafx.scene.control.Spinner;
import javafx.scene.control.SpinnerValueFactory;
import javafx.scene.control.DatePicker;

public class RegistController {
	@FXML
	private Button HomeButton;
	@FXML
	private Button logoutButton;
	@FXML
	private Button RegistButton;
	@FXML
	private Button RiwayatButton;
	@FXML
	private Label dateLabel;
	@FXML
	private Label timeLabel;
	@FXML
	private Label user;
	@FXML
	private TextField namaTextField;
	@FXML
	private TextField nimTextField;
	@FXML
	private Spinner<Integer> umurSpinner;
	@FXML
	private TextField kelasTextField;
	@FXML
	private DatePicker tanggalDatePicker;
	@FXML
	private ComboBox<String> jamCombobox;
	@FXML
	private TextArea keluhanTextArea;
	@FXML
	private Button submitButton;
	@FXML
	private Label userLabel;
	
	public TextField getNamaTextField() {
        return namaTextField;
    }

    public TextField getNimTextField() {
        return nimTextField;
    }

    public Spinner<Integer> getUmurSpinner() {
        return umurSpinner;
    }

    public TextField getKelasTextField() {
        return kelasTextField;
    }

    public DatePicker getTanggalDatePicker() {
        return tanggalDatePicker;
    }

    public ComboBox<String> getJamCombobox() {
        return jamCombobox;
    }

    public TextArea getKeluhanTextArea() {
        return keluhanTextArea;
    }
    
    private SubmitCommand submitCommand;

    public RegistController() {
        submitCommand = new SubmitCommand(this);
    }

	// Event Listener on Button[#HomeButton].onAction
	@FXML
	public void homeView(ActionEvent event) {
		// TODO Autogenerated
		Parent homeViewParent = ViewFactory.loadView("/view/HomeView.fxml");
        if (homeViewParent != null) {
            Scene homeViewScene = new Scene(homeViewParent);
            Stage window = (Stage) ((Node) event.getSource()).getScene().getWindow();
            window.setScene(homeViewScene);
            window.show();
        }
	}

	// Event Listener on Button[#RegistButton].onAction
	@FXML
	public void registView(ActionEvent event) {
		Parent registViewParent = ViewFactory.loadView("/view/RegistView.fxml");
        if (registViewParent != null) {
            Scene homeViewScene = new Scene(registViewParent);
            Stage window = (Stage) ((Node) event.getSource()).getScene().getWindow();
            window.setScene(homeViewScene);
            window.show();
        }
	}
	// Event Listener on Button[#RiwayatButton].onAction
	@FXML
	public void riwayatView(ActionEvent event) {
		Parent riwayatViewParent = ViewFactory.loadView("/view/RiwayatView.fxml");
        if (riwayatViewParent != null) {
            Scene homeViewScene = new Scene(riwayatViewParent);
            Stage window = (Stage) ((Node) event.getSource()).getScene().getWindow();
            window.setScene(homeViewScene);
            window.show();
        }
	}
	// Event Listener on Button[#logoutButton].onAction
	@FXML
	public void logout(ActionEvent event) {
		// TODO Autogenerated
        Sesi.clear();
        // Navigate to the login view
        Parent loginViewParent = ViewFactory.loadView("/view/LoginView.fxml");
        if (loginViewParent != null) {
            Scene homeViewScene = new Scene(loginViewParent);
            Stage window = (Stage) ((Node) event.getSource()).getScene().getWindow();
            window.setScene(homeViewScene);
            window.show();
        }
	}
	// Event Listener on Button[#submitButton].onAction
	@FXML
	public void submitForm(ActionEvent event) {
		// TODO Autogenerated
		submitCommand.execute(event);
	}
	
	@FXML
    public void initialize() {
        // Contoh set date dan time, bisa ditambahkan logic untuk mendapatkan date dan time sebenarnya
    	updateDateTimeLabels();
    	jamCombobox.getItems().addAll(
                 "08:00 AM", "08:30 AM", "09:00 AM", "09:30 AM", "10:00 AM",
                 "10:30 AM", "11:00 AM", "11:30 AM", "01:30 PM", "02:00 PM", 
                 "02:30 PM"
        );
        SpinnerValueFactory<Integer> valueFactory = new SpinnerValueFactory.IntegerSpinnerValueFactory(0, 50, 18);
        umurSpinner.setValueFactory(valueFactory);
    	Timeline timeline = new Timeline(
                new KeyFrame(Duration.seconds(1), event -> updateDateTimeLabels())
        );
        timeline.setCycleCount(Animation.INDEFINITE);
        timeline.play();
        
        User currentUser = Sesi.getCurrentUser();
        if (currentUser != null) {
            nimTextField.setText(currentUser.getNim());
            userLabel.setText(currentUser.getNim());
        }
    }
    
	// Method untuk update timeLabel secara realtime
    private void updateDateTimeLabels() {
        // Update tanggal dan jam secara realtime
        dateLabel.setText("Tanggal : " + LocalDate.now());
        timeLabel.setText("Jam       : " + LocalTime.now().toString().substring(0, 8));
    }

	public void clearForm() {
		// TODO Auto-generated method stub
		namaTextField.clear();
    	umurSpinner.getValueFactory().setValue(18); // Reset the spinner value if needed
    	kelasTextField.clear();
    	tanggalDatePicker.setValue(null);
    	jamCombobox.getSelectionModel().clearSelection();
    	keluhanTextArea.clear();
    	userLabel.setText(""); 
	}
}
